apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: {{ .Values.mongoexpress.servicePort }}
      targetPort: {{ .Values.mongoexpress.containerPort }}
      nodePort: {{ .Values.mongoexpress.nodePort }}
